### ISSUE TITLE
Cannot include 'freetype.lib'

### ISSUE THREAD

**Issue by SightDev** [nxseal/lw-with-gs-menu#1]
But where in the linker would I do the including of the file

**Comment by tuttizpro218** [comment]
![image](https://user-images.githubusercontent.com/21006560/182914379-8b3e5598-271b-401c-9280-ab66939934e7.png)
git gut get brain

**Comment by WILDM1hi** [comment]
> ![image](https://user-images.githubusercontent.com/21006560/182914379-8b3e5598-271b-401c-9280-ab66939934e7.png) git gut get brain

this is not working so stfu stupid fuck

**Comment by WILDM1hi** [comment]
> But where in the linker would I do the including of the file

this file is just broken, in Visual Studio find file called"freetype.lib" and delete it. Then download this fixed file:https://anonfiles.com/4fJam928yb/freetype_lib and drop it to the project, for me it helped

**Comment by PowerfullPower** [comment]
i guess link error is bigger problem
![image](https://user-images.githubusercontent.com/88488215/183002633-2438ee61-86fb-42c5-90ca-7311df02e176.png)

**Comment by nxseal** [comment]
> But where in the linker would I do the including of the file

try to google bruhhh

**Comment by tuttizpro218** [comment]
> 

it worked for me so user issue gg

**Comment by nxseal** [comment]
> > 
> 
> it worked for me so user issue gg

that's nice
